// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-CkkBQTzZ7sY5zc692qjlaOY93YIPjSU',
    appId: '1:517604211348:web:4880dd59471ee565e5d281',
    messagingSenderId: '517604211348',
    projectId: 'spotifahh168',
    authDomain: 'spotifahh168.firebaseapp.com',
    storageBucket: 'spotifahh168.firebasestorage.app',
    measurementId: 'G-W5YJXC7EJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxZQcrUww73-qeSd9jvLtZTfJiiOtRznc',
    appId: '1:517604211348:android:adc95ac2b31381dce5d281',
    messagingSenderId: '517604211348',
    projectId: 'spotifahh168',
    storageBucket: 'spotifahh168.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ3k-IXY7gBOkYkRiBiAKi1a-rv2p1xyw',
    appId: '1:517604211348:ios:90da8a8770fe437de5d281',
    messagingSenderId: '517604211348',
    projectId: 'spotifahh168',
    storageBucket: 'spotifahh168.firebasestorage.app',
    iosBundleId: 'com.example.spotifahh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ3k-IXY7gBOkYkRiBiAKi1a-rv2p1xyw',
    appId: '1:517604211348:ios:90da8a8770fe437de5d281',
    messagingSenderId: '517604211348',
    projectId: 'spotifahh168',
    storageBucket: 'spotifahh168.firebasestorage.app',
    iosBundleId: 'com.example.spotifahh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-CkkBQTzZ7sY5zc692qjlaOY93YIPjSU',
    appId: '1:517604211348:web:9432351033d1a5f0e5d281',
    messagingSenderId: '517604211348',
    projectId: 'spotifahh168',
    authDomain: 'spotifahh168.firebaseapp.com',
    storageBucket: 'spotifahh168.firebasestorage.app',
    measurementId: 'G-WZ5Q10WCM5',
  );
}
